### ISSUE TITLE
RFE: Forcing nozzle number from Run Job Window

### ISSUE THREAD

**Issue by lpuser13** [jkuusama/LitePlacer-DEV#104]
On the run Job window, the Nozzle number is displayed, which is good.

Consider changing this to a dropdown box, where the user can select another nozzle number 0-6 (it should behave like the Force Status button on the Nozzles Setup window).

tia :)

**Comment by jkuusama** [comment]
Saves a few clicks sometimes, but complicates already complicated UI.
