### ISSUE TITLE
RFE: Add go to Last Hole) button on the Tape Positions Window

### ISSUE THREAD

**Issue by lpuser13** [jkuusama/LitePlacer-DEV#105]
A Goto Hole 1 button already exists.

Consider adding a goto Last Hole button (useful when setting things up etc)

**Comment by jkuusama** [comment]
Will add this when the software manages number of parts in the tape in other aspects as well (like give warning if nmot enough parts etc). For now, this can be done in "Alignment test" section, where you can input a part number and go to the part or to the hole location.
