### ISSUE TITLE
Fiducials - To Display button doesnt set Find circles checkbox

### ISSUE THREAD

**Issue by lpuser13** [jkuusama/LitePlacer-DEV#106]
Window: Setup Cameras

When clicking the **To Display** button, all the **functions** are copied correctly.

However, The **Find Circles** checkbox doesn't reflect the saved value from before.

Not sure if this happens 100% of the time?...I think it also happens on homing, paper tape etc

**Comment by lpuser13** [comment]
This appears fixed (or redundant) in latest beta LitePlacer_beta_04_04

@jkuusama please close, if correct

**Comment by jkuusama** [comment]
Not relevant anymore, forgot to close
