### ISSUE TITLE
RE-measure when no 'homed'

### ISSUE THREAD

**Issue by lpuser13** [jkuusama/LitePlacer-DEV#115]
I accidently pressed the re-measure button, after the Home button turned red and the LP was in the parked position..

The re-measure function proceeded even though the coordinates were 'uncertain' (?)

I presume this is not intended and suggest that a Homing sequence be inserted before the 're-measure' if the HOME status is invalid or timed-out (i.e. Home button is Red)

**Comment by jkuusama** [comment]
Added to all operations that cause movement or relies on position being valid (v2 only)
