### ISSUE TITLE
All component are placed x:-0.1mm and y:+0.2mm wrong

### ISSUE THREAD

**Issue by rennne** [jkuusama/LitePlacer-DEV#121]
All components are placed -0,1mm in X direction and 0,2mm in Y direction wrong.

Direction or type does not have any influence.
I have expreieced it with about 40 different types of components placed in all 4 directions. on three different pcb's

The only way to correct for that I found so far is to change the position of the feducials in the placement file generated by kicad (Fiducial_1mm_Dia_2mm_Outer).

Every now and then when I switch on the liteplacer it is less pronounced but still there.

Maybe I build something wrong, or it is maybe some kind of rounding-issue in the software

**Comment by jkuusama** [comment]
not a general issue, removing from whole software issue list
