### ISSUE TITLE
Typo, in Select Method popup window (Run Job tab)

### ISSUE THREAD

**Issue by lpuser13** [jkuusama/LitePlacer-DEV#125]
Change to **Decide** (from dedice)

Version: 1.0.7371.3964, build date: 03/07/2020 02:12:08 [and earlier]

![TYPO 2020-03-08 17_50_01-Select Method](https://user-images.githubusercontent.com/54750135/76168245-cdc43300-6165-11ea-8b99-310a25e8db54.png)

**Comment by jkuusama** [comment]
Thanks! Fixed.
