### ISSUE TITLE
TinyG Error after Y-Homing

### ISSUE THREAD

**Issue by rennne** [jkuusama/LitePlacer-DEV#127]
During Homing the machine move into the switch and retracts slowly. Sometimes right after the switch releases a TinyG Error happens. I checked my wiring, it is ok.

After that I have to switch it off and on again. When trying a few times in usually works.

I assume it is caused by long bouncing of that limitswitch.

**Comment by jkuusama** [comment]
It can also be interference (some other switch activating). The switch might be bad. Also, you can tune the retraction speed. Send $xlv to find out the current value for X and $ylv for Y. Set new value by $xlv=500 (or whatever value you want).

Best regards

Juha
