### ISSUE TITLE
Feature request: Add functionality to save / reload tape and component positions and configuration

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#13]
Add functionality to save tape / component positions to file and reload the definitions from said file at a later time.

This would be of great help when working with custom component trays / jigs.

See related discussions here:
http://liteplacer.com/phpBB/viewtopic.php?f=11&t=64
http://liteplacer.com/phpBB/viewtopic.php?f=4&t=33

As a bonus: When loading a file it would be great if we had the option of either replacing the tape positions already configured in dialog by those from file or simply append the ones from the file. The latter would allow to combine multiple component trays.

**Comment by jkuusama** [comment]
Added tray support, which includes this.
