### ISSUE TITLE
tape.cs::IncrementTape() method, int.TryParse() fails

### ISSUE THREAD

**Issue by zrecore** [jkuusama/LitePlacer-DEV#15]
It seems the following code inside of the IncrementTape() method (below line 498) attempts to call the int.TryParse() method on the Id_Column value (which evaluates to column names such as "R1", or "L10").

The real issue appears to be as simple as using "Next_Column" instead of "Id_Column" like the other functions available in tapes.cs (though keep in mind, attempting to call TryParse() on "Id_Column" values such as "L10" would fail, since TryParse() only ignores spaces, and will return false when non-numerical characters are encountered).

```
int pos;
if (!int.TryParse(Grid.Rows[Tape].Cells["Id_Column"].Value.ToString(), out pos)) 
{
  // ....
}
```

I have changed it to the following. I'll have a merge request submitted shortly:

```
            int pos;
            string val = Grid.Rows[Tape].Cells["Next_Column"].Value.ToString();

            if (!int.TryParse(val, out pos))
            {
                MainForm.ShowMessageBox(
                    "Bad data at Tape " + Grid.Rows[Tape].Cells["Next_Column"].Value.ToString() + ", next",
                    "Sloppy programmer error",
                    MessageBoxButtons.OK
                );
                return false;
            }
```

**Comment by jkuusama** [comment]
Copy paste error, fixed.
