### ISSUE TITLE
RFE: Optionally use one of 2 or 3+ nozzles for each component in a job

### ISSUE THREAD

**Issue by AnalysIR** [jkuusama/LitePlacer-DEV#169]
I  am not sure is this would be useful to many, but could improve job run-time for some by avoiding nozzle changes.

-  I suspect that more than 1 nozzle size  would work for the same component.
-  Currently there is a 1 to 1 mapping of nozzle to component in a job
-  Allowing 2 or more mappings to each component, would mean that the nozzle would not necessarily have to be changed in some situations
-  This could be achieved by entering a a list of nozzles (2,3 or 2-3 or 2/3) instead of 2 for a component's nozzle, when associating a nozzle with a component for a job. The first in the list would be the preferred nozzle (2), but if the previous component used nozzle(3) then no nozzle change would occur and 3 would be used instead of 2. However if the next component was only nozzle 2 then nozzle 2 would be swapped in as a change was going to happen anyway on the next component.
-  Of course this could be configured manually if the user takes extra care in setting up each job. In this case a documentation note could suffice to highlight the potential time saving in using an alternative nozzle.

Potentially saving 1 or 2+ nozzle changes in a job could be a material time saving as a % of job runtime.

This is not urgent for me, but worth noting here for future reference.

**PS:** On a similar note an option to auto sort components by nozzle # in a job might be useful.

_(feel free to close if it doesn't make sense)_

**Comment by jkuusama** [comment]
Tooltip for nozzle column now tells that you can sort the job table rows by nozzle number by clicking the column. (The feature has always been there, just hidden.) Documentation is also updated to tell this. 
Having more than one nozzle for a component makes sense, but the benefit is small, compared to this (now visible) feature.
