### ISSUE TITLE
Tooltip text needs clarification for the "Load/set Current Position" buttons

### ISSUE THREAD

**Issue by Eriond** [jkuusama/LitePlacer-DEV#170]
The **Load Current Position** and **Clear Current Position** buttons in the bottom section of the window, have the same tooltip text. That makes the buttons' function unclear. I propose a text that is unambiguous, such as "Load the current nozzle position into the A-X boxes above, overwriting the content of all four boxes" and "Use the values in the A-X boxes as current nozzle position. Warning! This means that the nozzle will no longer be referenced to the home position"
Or something along those lines :)

**Comment by jkuusama** [comment]
Thanks! The set position button tooltip now reads "Set current coordinates to X-A boxes content. Warning! Coordinates are no longer referred to homing results."

**Comment by AnalysIR** [comment]
Referenced is better than referred .....

Just saying Coordinates is also ambiguous to me.  Are you saying they are now referenced to machine (limit switches) vs after the homing sequence.

It might be better if you changed the colour in the xyza boxes to indicate if the machine is now operating using the 'homed' coords or the physical machine coords.

**Comment by jkuusama** [comment]
Hmm, this is not as clear as I thought it would be. When you click the button, the current coordinates are set from the boxes. What actually happens depends on where the machine is and what is in the boxes. Maybe this is more confusing than useful?

AnalysIR.com ***@***.***> kirjoitti 17.8.2022 kello 15.19:

﻿

Referenced is better than referred .....

Just saying Coordinates is also ambiguous to me. Are you saying they are now referenced to machine (limit switches) vs after the homing sequence.

It might be better if you changed the colour in the xyza boxes to indicate if the machine is now operating using the 'homed' coords or the physical machine coords.

**Comment by AnalysIR** [comment]
OK..
I seems you want to say that 0,0,0,0 (XYZA) is no longer the home origin based on the manual changes made, which is sort of obvious given the coords were changed. Maybe think about changing the home button to orange (vs red / grey) as a persistent indicator that coords have been manually changed by user (Until machine is Homed again).
