### ISSUE TITLE
Feature request: Add functionality to manually calibrate pickup + place height / Z-level

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#18]
I would like a feature to manually calibrate the pickup height / z-level for component pickup and placement.

This is currently determined implicitly using the micro switch. I envision an additional function that allows a the user to teach the machine the correct pickup and placement height using jog controls - similar to needle height and backoff calibration.

Two use cases for that:
- Using strip / cut tape feeders that guide the tape on the sides to support variable height component, like in this picture
  ![strip_feed](https://cloud.githubusercontent.com/assets/10500490/9574774/476848c0-4fca-11e5-8cf4-5a17fee55015.jpg)
- pickup placement of sensitive components for which the pushing force of the needle (about 3N on my machine until switch trips) is too high (e.g. large electrolytic capacitors, IC)

**Comment by jkuusama** [comment]
The placement force can now be tuned. You can also edit the pickup height on each tape. This feature in other words is "Add a buttom to copy current Z to tape pickup value". Makes sense. On the other hand, the whole tape page needs a rewrite, Clear up and maybe a wizard. This might have to wait until then, as the manual workaround might not be that bad.

**Comment by mrandt** [comment]
The new setting for "placement depth" and ability to tune the "Pickup Z" and "Placement Z" parameters already solved my issue.

I can jog Z-axis to the right level and type the Z-coordinate into that field. Copy that with the click on a button would just be a convenience function - less important.

If you were to create a wizard to add a component location, this calibration might be and optional part in it. 

I suggest to close the issue for now.
