### ISSUE TITLE
Which is the correct 'development' repository/branch?

### ISSUE THREAD

**Issue by zrecore** [jkuusama/LitePlacer-DEV#19]
Hi @jkuusama, I'd like to contribute to a refactor. What repository should be forked in order to contribute?

I'd like to help develop the next version of the LitePlacer application.

Specifically, I hope to address the following:
- Tests
- UI should be responsive
- Camera API needs to be asynchronous (do not depend on while() loops w/ delay, as thr camera may take longer than expected to become available, causing infinite loops)
- Tape feeder mode (advance a tape reel)
- Documentation of software architecture

**Comment by jkuusama** [comment]
LitePlacer-DEV is the rep I'm working on and support.
