### ISSUE TITLE
Application freezes when no USB-TTL converter / TinyG is connected

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#2]
When starting the application without hardware controller connected, it freezes completely on my machine (Win7 x64), bloats up memory usage and has to be killed via Task Manager.

From first investigation, issue seems to be located in `LitePlacer.SerialComm.Write` or further up the call hierarchy...

I believe when no device is connected, communication should time out and TinyG should automatically go to "disconnected" state on UI.

**Comment by jkuusama** [comment]
> I believe when no device is connected, communication should time out and TinyG should automatically go to "disconnected" state on UI.

Of course, that is how it should behave – and does, on my Win8 machine. I’ll investigate.

Best regards,

Juha

**Comment by mrandt** [comment]
This seems fixed with latest versions. If no TinyG connected, application gracefully goes to "disconnected" state. Suggest close.
