### ISSUE TITLE
Tape positions  crashes when doing something stupid 

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#20]
See:
http://i.imgur.com/DXjpD3L.png

I accidentally loaded a custom tapes file into tape potions. Now it crashes whenever you look at it.

Now I know what I did was not normal behavior but the exception should be handled.

**Comment by jkuusama** [comment]
Old bug report, that I can't reproduce in the current version. Fixed by side-effect, I think,
