### ISSUE TITLE
Select method Recalibrate does nothing?

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#21]
Select method Re-calibrate does nothing?
I put this in a line because I wanted it to re-calibrate at that step.
Did nothing , continued at next component.

Might be also smart to have multiple levels of recal:
1 - only feducials
2 - needle and feducials
3 - home needle feducials

**Comment by jkuusama** [comment]
Fixed some time ago, but forgot to make a note about it.
