### ISSUE TITLE
Tapes: When next part is changed manually

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#22]
Tapes: When next part is changed manually changed back to one or whatever the next part x,y is not automatically changed.

I.e. I changed it to part 1 , it thinks next part is at part 17

**Comment by mrandt** [comment]
Bug still exists in version 17_11_2015. 

If I manually change the number in "Next" column (Tape Positions List), Next X and Next Y should be updated.

Also, when executing "Set Hole 1" I would assume that Next X and Next Y should be updated.

**Comment by mrandt** [comment]
Copy & pasted related issue from: http://liteplacer.com/phpBB/viewtopic.php?f=10&t=208#p1478

If you:
1) Move to first component's hole
2) Add component
3) Set component hole
is works fine.

BUT, if you:
1) Click Add component
2) Move to first component's hole
3) Set component's hole
then program (wrong) takes "Next" position from the last hole added (previous component) and when you set component's hole, "next" position isn't turned into component's hole, but stays the same.

**Comment by mrandt** [comment]
I have fixed these issues in code and created a pull request for my changes:
https://github.com/jkuusama/LitePlacer-DEV/pull/37

Please check and merge to main branch.
