### ISSUE TITLE
Bug: Not taking correct pnp csv colum

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#24]
When using altium there are more than one XY coordinate.

It seems to use Ref X and Ref Y. Some footprints have these in pin 1.
That is why altium also includes Mid X and Mid y coordinate to combat that.

So it seems that Mid X and Mid Y need to be used for altium.
http://i.imgur.com/TFITsWP.png

Sample file:
https://mega.nz/#!dJtXGC4T!pFb17wAJggP9GT5SZ-zh6j1TPb7rPpbTWloRCpBEZto

**Comment by jkuusama** [comment]
Fixed.
