### ISSUE TITLE
Bug: not taking into account inverted x coordinate when placing bottom

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#25]
When placing the bottom of a pcb the coordinates are inverted because they are looked upon from the top side of the pcb:

File:
https://mega.nz/#!dJtXGC4T!pFb17wAJggP9GT5SZ-zh6j1TPb7rPpbTWloRCpBEZto

If you do x offset -100 mm they are in the correct location

bottom:
![image](https://cloud.githubusercontent.com/assets/8618634/10848527/95a034b8-7f1c-11e5-81d8-fed4a272b169.png)

top:
![image](https://cloud.githubusercontent.com/assets/8618634/10848534/accb0f78-7f1c-11e5-92fb-0fac14bab17b.png)

It is not possible to have a separate coordinate system in altium or change it to be in the "right" direction.

**Comment by jkuusama** [comment]
As designed, but not properly documented. I added a page about this: http://www.liteplacer.com/double-sided-boards/ .
