### ISSUE TITLE
Bug: placing bottom layer components rotated 180 degrees

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#26]
When placing the bottom of a pcb Altium says they are rotated 180 degrees.

To combat this all rotations on the bottom layer should be deducted by 180 degrees to get the correct orientation.

I think this is also the case in other cad packages.
File:
https://mega.nz/#!dJtXGC4T!pFb17wAJggP9GT5SZ-zh6j1TPb7rPpbTWloRCpBEZto

Device on bottom layer:
![image](https://cloud.githubusercontent.com/assets/8618634/10848619/28a06aee-7f1d-11e5-8c3d-548c2882a8e9.png)

pnp file:
![image](https://cloud.githubusercontent.com/assets/8618634/10848633/3c3fb226-7f1d-11e5-8a1f-381d92c2872b.png)

**Comment by DC37** [comment]
I seem to get similar issues even on the top layer - sometimes, the machine insists on doing a 180-degree turn to pick up the part (even when I have the part orientation set to 180 on the tape) and then undoes it when it goes to place the part.

**Comment by jkuusama** [comment]
Fixed. [http://www.liteplacer.com/double-side-data-handling/](url)

**Comment by jkuusama** [comment]
Is the result wrong or just that it does unnecessary rotations? If result is wrong, do you have a file and a setup where this is reproducible?

**Comment by DC37** [comment]
The machine just does unnecessary rotations.

**Comment by jkuusama** [comment]
I could make another issue for optimizing the movements. However, the rotation is not the limiting factor and there are much more beneficial issues to tackle; in honesty, I don't think that issue would ever get attention. This peculiarity can stay.

**Comment by DC37** [comment]
Yup, no worries.
