### ISSUE TITLE
Can't place components when there are no feducials?

### ISSUE THREAD

**Issue by BuildItAnyway** [jkuusama/LitePlacer-DEV#27]
Can't place components when there are no fiducial

Due to the fiducial measurement being off one would want to place components without this compensation. But it seems not to be possible?

**Comment by jkuusama** [comment]
The system needs to map nominal (CAD) coordinates to machine coordinates. Currently, this is done By fiducials, and you could use vias or mounting holes as fiducials as well. How?
- It would be rather difficukt to put board manually down accurately enough, but I guess it could be done. Are you suggesting adding a capability to do this?
- Some other mapping method?

**Comment by TheYieldPoint** [comment]
My pcb zero point is really accurate. Due to the boards being cnc routed this is also pretty accurate.
I used mounting holes as fiducials. The nominal locations were more accurate than the measured locations.

I would just implement it as an option:
Do you want to use fiducials or place as is?

**Comment by hzeller** [comment]
What I did before (in some PCB processing software I wrote) was to use SMD pads of two components far away on the board to use as "fiducials".

So maybe if the software knows where the pads are, then it can pick two components and find the pads and use these to align the board internally (possibly with assistence by the user 'is this really the right pad of D7' or something).

**Comment by TheYieldPoint** [comment]
Normally I have fiduacials but I kinda forgot to place them.
The method @hzeller proposed would also work.

**Comment by jkuusama** [comment]
The latest commit has checkboxes for skipping both needle calibration (requested privately) and board measurement. I didn't have much time to check that before I had to go for a weekend trip with my family, but you can try it out.

**Comment by TheYieldPoint** [comment]
Ok thanks. I have exams this week so not much time.
A good reference for vision stuff is the book "Digital Image Processing ISBN-13: 978-0-13-234563-7". I'm currently doing my minor in this subject and will be able to contribute when I have more time.

**Comment by jkuusama** [comment]
Using vias or other round pads works. This has to do for a while. I'm  cleaning up the repo and closing this issue, as I won't do anything for it at this point.
