### ISSUE TITLE
Feature request: Manually teach first and last part position using camera (not sprocket holes)

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#29]
I would like a function to manually teach first and last part position.

There are situations in which sprocket holes are difficult to detect or not even available (e.g. custom trays) but components are still arranged in a repeating pattern / equally spaced.

Procedure: 
1. Jog camera over first part's center and store first part location
2. Jog to last part and also store location. 
3. Input number of available components.
4. Other configutation for part position (component orientation, pickup levels, etc.) should stay the same
4. Software calculates part positions based on equal spacing and calculates tape / tray direction and rotation.

This would rely on #28.

**Comment by caprisonne** [comment]
I fully support this proposal. It would be the fallback-function for the currently missing up-camera offset correction (https://github.com/jkuusama/LitePlacer-DEV/issues/34). It would be an important help to place ICs with very little distances between the pins .

**Comment by jkuusama** [comment]
(Cleaning up old requests)
This is the "use coordinates directly" option in tape edit dialog. You don't give the number of coordinates, but the pitch of the tape; same result.
