### ISSUE TITLE
Feature request: Port auto calibration routines from RMOD / VER2

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#30]
Reza's mod of the software had some nice additional automatic calibration routines.

It would be great if those were ported to the main branch.

In particular:
- Determining pixel-to-mm ratios for down and up camera by moving gantry and measuring effective homing mark / needle move with computer vision; way more accurate than measuring box size with a ruler
- Auto-centering needle (set camera position) above up camera using computer vision
- New and improved way of measuring, visualizing and validating the compensation of needle wobble

**Comment by jkuusama** [comment]
All have been in the software for long time. Forgot to close the issue.
