### ISSUE TITLE
Feature request: Rotation preview for parts and placement location on PCB

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#36]
This is a X-post of https://github.com/jkuusama/LitePlacer-ver2/issues/13

I think it is a minor enhancement but a great usability improvement.

In "Run Job" tab I can preview the location of each component by selecting it from the list and clicking "Measured location". 

In addition to the coordinates (crosshairs), I would like to see the component rotation in the camera preview as well.

We could use a different color arrow similar to following mockup - showing a part location with 30° rotation from Juha's "Hello World" file:

![mrandt_part_orientation](https://cloud.githubusercontent.com/assets/10500490/11255010/2cbdbde4-8e44-11e5-93f8-566774fc13b4.png)

(Please note that the picture in my original issue for Ver-2 was wrong).

I would also like to see the orientation of parts when configuring "Tape positions" in a similar fashion - so when I set 90° for "Rot." I would expect something like this:

![mrandt_part_orientation_tape](https://cloud.githubusercontent.com/assets/10500490/11255219/3f21f030-8e45-11e5-8cf8-13a4d883eeab.png)

Together, these functions would allow me to check if the orientation both for pickup and placement will be correct without actually placing the parts. 

This would make setting up a new job simpler and cause me and other less headaches.

**Comment by mrandt** [comment]
Karl or Reza added part of this functionality in their Ver-2 forks. The component orientation is previewed in part / tape position configuration. I noticed this when testing Karl's version but it may have been there before.

**Comment by jkuusama** [comment]
Done.

**Comment by mrandt** [comment]
Please reopen this issue. Latest release 05_02_2016b broke the preview in tape positions dialog.

Clicking "Show Hole" or "Show Part" does not do anything anymore.

![part_preview](https://cloud.githubusercontent.com/assets/10500490/13196749/b27d2e42-d7d7-11e5-9af3-285f34710935.png)

As an additional feature request, I'd like a function "Show part on tape" in the CAD Data list of "Run Job" tab. 

When clicking the button, the cam should go to the next part of the part / component mapped in Job data config and preview the pickup location + rotation. 

Karl's fork does have this feature and it is very convenient to confirm you've set up everything correctly.

**Comment by jkuusama** [comment]
This needed part number in the box (always did). Now it uses the next part if the box is empty. Show part on run job is a good idea, will do.
