### ISSUE TITLE
Home X times out on larger machine size - increase timeout?

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#4]
My LitePlacer clone is 630 mm wide. If machine is positioned far right and I attempt to home X axis, the travel takes too long and I get a timeout before the limit / home switch is tripped.

I think the timeout should ideally be derived from safe area X dimension.

**Comment by MaWa53** [comment]
I have a standard LitePlacer (590 mm wide) and I get a timeout too, when I home from the far upper right.

**Comment by jkuusama** [comment]
Fixed. Timeout value now comes from machine size.
