### ISSUE TITLE
loading "bottom" parts with negative coordinates doesn't work

### ISSUE THREAD

**Issue by se6astian-pi** [jkuusama/LitePlacer-DEV#45]
When using a PCB that has the origin in the middle and using job offset importing CSV for top side works fine.
But when trying to load the bottom side by clicking the "bottom" checkbox next to the CAD Data label liteplacer tries to mirror coordinates by turning positive X values negative, if the value is already negative an error message pops up:

![bottom-pcb-error](https://cloud.githubusercontent.com/assets/4028409/21467060/e1bf5ea0-c9df-11e6-9af7-4907204dec02.png)

**Comment by jkuusama** [comment]
Fixed by tinic (thank you!)
