### ISSUE TITLE
Support for LED placement?

### ISSUE THREAD

**Issue by kegsay** [jkuusama/LitePlacer-DEV#46]
Hello! Is LitePlacer able to correctly orientate 5mm LEDs (e.g. by recognising the outline using the built-in camera)? If not, is this due to fundamental limitations of the camera, or just because there isn't an accurate enough algorithm?

Thanks!

**Comment by MaWa53** [comment]
The camera is not the issue. The algorhythm has been defined by jason von nieda in openpnp for the up looking camera which can also be used for the down cam. But the needed steps are not yet available in the liteplacer software. You need to adjust the angle addtionally to the x and y location. For 5mm LEDs the recognition works very well with white case material.

**Comment by kegsay** [comment]
Thanks for the quick reply! Are there any plans to support LED placement in the near future? Is there any way I can help?
