### ISSUE TITLE
wm_close needs to be ignored

### ISSUE THREAD

**Issue by j-east** [jkuusama/LitePlacer-DEV#47]
I'm pressing alt F5 a lot to move the machine around. If I misclick I hit alt-F4 which terminates the program. I found the following technique to avoid that:

```
private void MainForm_FormClosing(object sender, FormClosingEventArgs e) {
    var window = MessageBox.Show(
        "Close the window?", 
        "Are you sure?", 
        MessageBoxButtons.YesNo);

    e.Cancel = (window == DialogResult.No);
}
```

and it should need to be added to the event handler in the designer

**Comment by jkuusama** [comment]
Fixed, but I put the fix where jogging keys are handled. No dialog if you close from window corner.
