### ISSUE TITLE
Pump is not switched on when placing parts!

### ISSUE THREAD

**Issue by petegit** [jkuusama/LitePlacer-DEV#56]
Recently I updated my old fork to the newest version. Now I have the problem that when I start placing parts the pump is not switched on. After start of program Pump On & Vacuum On(solenoid valve) is marked as on, so the program thinks that the pump is already switched on. To get it work I need to manually switch off the pump & solenoid valve in the Basic Setup tab. 

Using my old LitePlacer version which based on a version from 2016 I do not have this problem.

I think the problem may caused by the line commented with _// to force action_ 

        public void PumpDefaultSetting()
        {
            PumpIsOn = true;   // to force action
            PumpOff();
        }
In the function PumpOff() PumpIsOn is set to false, but only when the detected controler type is TinyG. The problem is that the controler type is detected after calling PumDefaultSetting(). The log also shows that the sequence is not rigth. 

Or could this be a timing problem? After starting the LitePlacer software it needs up to 8 seconds for connecting and reading out the TinyG settings and come to the question for homing.    

Version: 1.0.6788.24299, build date: 02.08.2018 13:29:58
Reading C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.Appsettings
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.HomingFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.FiducialsFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.ComponentsFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.PaperTapeFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.BlackTapeFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.ClearTapeFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.SnapshotFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.NozzleFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.Nozzle2Functions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.UpCamComponentsFunctions_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.UpCamSnapshotFunctions_v2
Loading tapes with nozzles data
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.TapesData_v2
Loading nozzle calibration data
Loading nozzle calibration validity data
Loading nozzles data
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.NozzlesLoadData_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.NozzlesUnLoadData_v2
Reading v2 format file C:\Entwicklung\LitePlacer-Juha\LitePlacer-DEV\LitePlacer\bin\Debug\LitePlacer.NozzlesParameters_v2
Using calibration for nozzle 1
Loading temp CAD data file
Loading temp job data file
UpCamera start, moniker= @device:pnp:\\?\usb#vid_046d&pid_0825&mi_00#7&74720d&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083}
*** Camera started: 21
DownCamera start, moniker= @device:pnp:\\?\usb#vid_5149&pid_13d3&mi_00#7&341cc276&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
*** Camera started: 45
DownCamera activated
Connected to serial port COM3
**PumpOff(), qQuintic  -- SKIPPED --
*** VacuumOff(), unknown board!!**
**_Finding board type:_**
==> {"hp":""}
<== {"r":{"hp":1},"f":[1,0,10,4985]}
TinyG board found.
ReadyEvent r
==> 
==> {sr:n}
<== {"r":{"sr":{"posx":0.000,"posy":0.000,"posz":0.000,"posa":0.000,"feed":0.00,"vel":0.00,"unit":1,"coor":0,"dist":0,"frmo":1,"stat":1}},"f":[1,0,7,726]}
ReadyEvent r:sr
Reading TinyG settings:
==> {"ec":""}
<== {"r":{"ec":0},"f":[1,0,10,5349]}
ReadyEvent r
==> {"ee":""}
<== {"r":{"ee":0},"f":[1,0,10,5432]}
.....

Regards,
Peter.

**Comment by jkuusama** [comment]
I believe the recet release fixed this.
