### ISSUE TITLE
Application window does not fit smaller screens - buttons hidden

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#6]
I have a 19" TFT permanently attached to my LitePlacer frame. The display has a resolution of 1440x900 which I believe is reasonable for the display size.

Unfortunately the LitePlacer application window does not fit the screen and when maximizing, some buttons and labels at the bottom are hidden from view and out of reach.

I believe, with a bit of rearranging and smart use of the space available, the application could still be made to fit smaller screens. Otherwise a scroll bar would be better than just hiding controls "off screen".

I will attach a screenshot later to illustrate the issue.

**Comment by mrandt** [comment]
See screenshot for illustration of the issue:

![2015-04-08 11_28_40-2015-04-08 10_13_06-liteplacer](https://cloud.githubusercontent.com/assets/10500490/7042551/0238c3e6-dde3-11e4-978b-bee95b36367c.png)

**Comment by jkuusama** [comment]
> I believe, with a bit of rearranging and smart use of the space available...
> For the Basic Setup screen, yes. A bigger issue is the Run Job screen, where it would be good to have the CAD data, the job data, the camera image and the buttons on the screen. The scroll bars are there now as a first aid, but I leave this open.

**Comment by mrandt** [comment]
I am not sure what display and resolution everybody else is using, but I still have to scroll when using my 1440x900 display. 

It probably got worse with latest versions as those have more controls on the bottom section... :-(

**Comment by mrandt** [comment]
I changed the layout to support 900px vertical resolution.

I have put the changes into a separate branch and created pull request:
https://github.com/jkuusama/LitePlacer-DEV/pull/38

**Comment by jkuusama** [comment]
This has been out for a while now without bad comments. Closing.
