### ISSUE TITLE
Using arduino due and g2core

### ISSUE THREAD

**Issue by qiwalker** [jkuusama/LitePlacer-DEV#61]
Hi... 
Can i use arduino due and g2core with liteplacer software

Thanks
Rizki

**Comment by jkuusama** [comment]
Hi,

Not directly. The software is open source; the needed modifications would not be big, if you handle the parameters setup elsewhere.

Best regards, Juha

qiwalker <notifications@github.com<mailto:notifications@github.com>> kirjoitti 19.4.2019 kello 15.18:


Hi...
Can i use arduino due and g2core with liteplacer software

Thanks
Rizki

**Comment by jkuusama** [comment]
Support for g2core accepted for development

**Comment by Symeth** [comment]
hi mr. Jkuusama

just for confirmation,
did liteplacer already support for g2Core ?

thanks

**Comment by jkuusama** [comment]
Hi,
No, and i is unlikely it ever will, as there are no commercially available boards apparently, none in the future either. There is work towards Reprap firmaware boards (in the processing tables branch), but that it not ready yet.

**Comment by jkuusama** [comment]
I will not do this. Reprap firmwareis much safer route.
