### ISSUE TITLE
Homing procedure potentially damages the machine (camera), if Z-Limit switch cable is broken

### ISSUE THREAD

**Issue by rennne** [jkuusama/LitePlacer-DEV#79]
I was trying to get the nozzle calibration to work, so I was changing the parameters form the image recognition, and thereby the nozzle was above the up looking camera.

During that the motors switched of and the program asked my if it should do "Homing".
I clicked Z went up and was rattling, obviously my cabling was not perfect and the Z-Limit switch cable broke.

I was not fast enough to realize what is happening and to press the reset button.
Instead of aborting the program continued, it went down and crashed the nozzle into the camera.

Lucky the nozzle was not exactly above the center of the lens so it was not really damaged.

**Comment by jkuusama** [comment]
Sensible limits and guards are good, but it is impossible to be prepared for all possible hardware malfunctions. :-(
