### ISSUE TITLE
Feature request: Avoid modality for informational messages

### ISSUE THREAD

**Issue by mrandt** [jkuusama/LitePlacer-DEV#8]
I believe application usability would benefit from removing modal popup messages in non-critical situations and introduce a status bar or other form of less intrusive notification instead.

Prominent example: Attempt to move machine outside safe area while jogging. It is sort of annoying to pick up the mouse, move to the dialog window and click OK just because I tried to go right when I wanted to go left. No point for modal here, as the machine does not move anyways...

I suggest to limit modal dialogs to situations where users absolutely MUST pay attention to the dialog and perform an action other than just clicking OK.

**Comment by MaWa53** [comment]
Proposal: add a jog button group and disable the "unallowed" buttons. Then the user can see why there is no further movement but does not have to answer the dialog. Stating the fact in the text log should add additional information.

**Comment by jkuusama** [comment]
Most are changed to log window messages. Log messages are prioritized in development. I forgot to close the issue in time.
